create table if not exists public.pt_workouts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  sort_order integer not null,
  unique(user_id, sort_order)
);

create table if not exists public.pt_exercises (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  workout_id bigint not null references public.pt_workouts(id) on delete cascade,
  name text not null,
  sets integer not null default 3,
  min_reps integer not null default 8,
  max_reps integer not null default 12,
  exercise_type text not null default 'compound',
  sort_order integer not null,
  unique(user_id, workout_id, sort_order)
);

create table if not exists public.pt_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  workout_name text not null,
  completed_at timestamptz not null default now()
);

create table if not exists public.pt_sets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id bigint not null references public.pt_sessions(id) on delete cascade,
  exercise_name text not null,
  set_number integer not null,
  weight numeric,
  reps integer,
  min_reps integer,
  max_reps integer
);

create table if not exists public.pt_body_weight (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  recorded_at timestamptz not null,
  weight numeric not null,
  unique(user_id, recorded_at)
);

alter table public.pt_workouts enable row level security;
alter table public.pt_exercises enable row level security;
alter table public.pt_sessions enable row level security;
alter table public.pt_sets enable row level security;
alter table public.pt_body_weight enable row level security;

drop policy if exists pt_workouts_owner on public.pt_workouts;
create policy pt_workouts_owner on public.pt_workouts for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists pt_exercises_owner on public.pt_exercises;
create policy pt_exercises_owner on public.pt_exercises for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists pt_sessions_owner on public.pt_sessions;
create policy pt_sessions_owner on public.pt_sessions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists pt_sets_owner on public.pt_sets;
create policy pt_sets_owner on public.pt_sets for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists pt_body_weight_owner on public.pt_body_weight;
create policy pt_body_weight_owner on public.pt_body_weight for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create index if not exists pt_workouts_user_idx on public.pt_workouts(user_id, sort_order);
create index if not exists pt_exercises_workout_idx on public.pt_exercises(workout_id, sort_order);
create index if not exists pt_sessions_user_idx on public.pt_sessions(user_id, completed_at);
create index if not exists pt_sets_session_idx on public.pt_sets(session_id);
create index if not exists pt_body_weight_user_idx on public.pt_body_weight(user_id, recorded_at);
